### fileJob 테스트
POST http://localhost:8080/job/fileJobLauncher
Content-Type: application/json

{
  "requestDate": "20230913"
}

### apiJob 테스트
POST http://localhost:8080/job/apiJobLauncher
Content-Type: application/json

### moveJob 테스트
POST http://localhost:8080/job/moveJobLauncher
Content-Type: application/json

### moveJob2 테스트
POST http://localhost:8080/job/moveJobLauncher2
Content-Type: application/json






